---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          icon: github-light.png
          href: https://github.com/

- Social:
    - Reddit:
        - abbr: RE
          icon: reddit.png
          href: https://reddit.com/
    - Airsoft Nexus:
        - abbr: AN
          href: https://airsoftnexus.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          icon: youtube.png
          href: https://youtube.com/
