---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

localdocker:
  host: dockerproxy
  port: 2375

dnsdocker:
  host: tcp://192.168.0.102:2376

# my-docker:
#   socket: /var/run/docker.sock
